In [1]:
import numpy as np


In [198]:
# Ej 3

def matSimPosDef(n):
    intervalo = [0,10]
    mat = np.random.rand(n,n)
    mat = np.tril((mat*intervalo[1])+intervalo[0], k=-1) + np.eye(n)*np.diag(mat*(intervalo[1]-1)+intervalo[0]+1)
    mat = mat@mat.transpose()
    return mat
matSimPosDef(3)

array([[ 38.22645014,  15.84586707,  43.67326731],
       [ 15.84586707,   8.11442896,  29.98875488],
       [ 43.67326731,  29.98875488, 219.26477219]])

In [247]:
# Ej 6

def factCholesky(A):
    L = np.tril(A)
    n = np.shape(A)[0]
    for s in range(n):
        L[s,s] = np.sqrt(L[s,s])
        L[s+1:, s] /= L[s,s]
        h = np.append(np.zeros((s+1,1)), L[s+1:, s])
        for j in range(s+1, n):
            for i in range(j, n):
                L[i,j] -= h[i]*h[j]
    return L
mat = matSimPosDef(3)
factCholesky(mat), np.linalg.cholesky(mat)

(array([[9.43277409, 0.        , 0.        ],
        [9.18264562, 1.3712782 , 0.        ],
        [4.52842814, 3.41838493, 7.7265928 ]]),
 array([[9.43277409, 0.        , 0.        ],
        [9.18264562, 1.3712782 , 0.        ],
        [4.52842814, 3.41838493, 7.7265928 ]]))

In [219]:
L = np.array(([1.0,1,1],[2,3,4],[5,7,9]))
print(L)
for s in range(len(L)):
    print(L[s,s+1:])
    L[s, s+1:] /= 2.0
    print(L[s,s+1:])

[[1. 1. 1.]
 [2. 3. 4.]
 [5. 7. 9.]]
[1. 1.]
[0.5 0.5]
[4.]
[2.]
[]
[]


In [248]:
# Ej 8

def factCholeskyRen(A):
    L = np.triu(A)
    n = np.shape(A)[0]
    for s in range(n):
        L[s,s] = np.sqrt(L[s,s])
        L[s, s+1:] /= L[s,s]
        h = np.append(np.zeros(s+1), L[s, s+1:])
        for i in range(s+1,n):
            L[i, i:] -= h[i]*h[i:]
    return L
mat = matSimPosDef(3)
factCholeskyRen(mat).transpose(), np.linalg.cholesky(mat)

(array([[4.52556041, 0.        , 0.        ],
        [6.04612302, 2.43541929, 0.        ],
        [8.18586237, 0.14463715, 4.80369197]]),
 array([[4.52556041, 0.        , 0.        ],
        [6.04612302, 2.43541929, 0.        ],
        [8.18586237, 0.14463715, 4.80369197]]))

In [250]:
# Slower ???
mat = matSimPosDef(5)
%timeit factCholesky(mat)
%timeit factCholeskyRen(mat)

87.6 µs ± 13 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
110 µs ± 17.5 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
